### ISSUE TITLE
Request: example pre-commit integration into README

### ISSUE THREAD

**Issue by jamesbraza** [IamTheFij/docker-pre-commit#11]
https://pre-commit.com/hooks.html advertises this repo as having `docker-compose-check`.

It would be cool to speed integration by providing an example `pre-commit` hook integration into the `README.md`.

For example, should this be integrated as a `local` hook like [this](https://github.com/IamTheFij/docker-pre-commit/blob/master/.pre-commit-hooks.yaml#L2) or can it be a normal `repo` hook?

**Comment by IamTheFij** [comment]
It's a normal pre-commit hook. You add it as you would any others you see on pre-commit.com.

Here's an example: https://github.com/claha/smart-home/blob/247f197bb05ed12537b4c3313e5826743d296a41/.pre-commit-config.yaml#L47

I'm hesitant to put an example because I don't want to deal with updating the pinned version,

**Comment by jamesbraza** [comment]
For posterity, the [contents of the above link](https://github.com/claha/smart-home/blob/247f197bb05ed12537b4c3313e5826743d296a41/.pre-commit-config.yaml#L47):

```yaml
  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
```

---

Yeah @IamTheFij I hear what you're saying on updating the pinned version.

What `hadolint` did in their [`INTEGRATION.MD`](https://github.com/hadolint/hadolint/blob/ece5a6b8633b81cc99f4d0ae5e200c7e3794c137/docs/INTEGRATION.md#pre-commit) was use `rev: master`.  That could be an option for you.

Otherwise, feel free to close this one out, and cheers!
